language: node_js

node_js:
  - "6"

env:
  - NODE_ENV=testing CC=clang CXX=clang++ npm_config_clang=1

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - xvfb
      - gnome-keyring
      - libgnome-keyring-dev
